### ISSUE TITLE
mnemonics are not found in Extention Manager collection when search

### ISSUE THREAD

**Issue by noufionline** [JetBrains/mnemonics#14]
After upgrading to 2016.2 mnemonics  are not listed in the Extensions collection

**Comment by citizenmatt** [comment]
Hmm. They should be. Could you please show me the content of ReSharper &rarr; Options &rarr; Extension Manager, please? Perhaps there's an issue with the feed settings.

**Comment by nesteruk** [comment]
I can definitely see them in Extension Manager.

**Comment by noufionline** [comment]
I have on extension source
.Net Product Gallery => https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v6.0/

**Comment by noufionline** [comment]
Tried to reinstall. but same effect. Please find the attached images.

![resharper missing extentions error](https://cloud.githubusercontent.com/assets/13216154/18076246/508e3e90-6e8d-11e6-99d4-980e6fcd44a9.PNG)
![resharper missing extentions error1](https://cloud.githubusercontent.com/assets/13216154/18076244/5083f5f2-6e8d-11e6-9345-e8fc1f24b71d.PNG)
![resharper missing extentions error2](https://cloud.githubusercontent.com/assets/13216154/18076245/50876cbe-6e8d-11e6-92dc-6e78194f5fdb.PNG)

**Comment by noufionline** [comment]
Oh! Sorry. But even if I Type *mne* I don't see it.

I can see altogether only 20 extensions

![resharper missing extentions error4](https://cloud.githubusercontent.com/assets/13216154/18087161/c29237f8-6ec4-11e6-8188-2c7fa1fae9b3.PNG)

**Comment by noufionline** [comment]
accidently closed. Sorry.

Can anyone help on this please???

**Comment by citizenmatt** [comment]
Hmm. I've just given the server a kick and it's definitely showing up now. Can you check again, please?

**Comment by noufionline** [comment]
It's Ok now :)
Thanks
