### ISSUE TITLE
Support Reshrper 9.1

### ISSUE THREAD

**Issue by borismod** [JetBrains/mnemonics#8]
I upgraded to Resharper 9.1 and mnemonics extension stopped working. Please support re#9.1

Thanks!

**Comment by nesteruk** [comment]
@citizenmatt can you help with this? since you posted the original NuGet package, only you have the right to update it, correct?

**Comment by citizenmatt** [comment]
Gah! I already did this, and forgot to update the issue, sorry. It's up on the gallery, check it out. (You might also want to check out [ZenSharp](https://github.com/ulex/ZenSharp#readme))
